import { readdir } from 'node:fs/promises'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const iconsDir = path.join(__dirname, '..', 'src', 'icons')
const outFile = path.join(__dirname, '..', './scripts/index.ts')

const files = (await readdir(iconsDir)).filter((f) => f.endsWith('.svg')).sort()

const isIdentifier = (s) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s)
const lines = files
  .map((f) => {
    const key = f.replace(/\.svg$/, '')
    const safeKey = isIdentifier(key) ? key : JSON.stringify(key)
    const value = JSON.stringify(`./icons/${f}`)
    return `  ${safeKey}: ${value},`
  })
  .join('\n')

const content = `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
export const icons = {
${lines}
} as const;

export type IconName = keyof typeof icons;
`

await writeFile(outFile, content, 'utf8')
console.log(`✓ Wrote ${outFile} with ${files.length} icons`)
