// Generate src/index.ts — the root bundle aggregator. Replaces the previously hand-maintained
// 417-line file so every layer (global/semantic) and theme is exposed uniformly across all
// formats. Colours: tokens.<format>.<global|semantic|themes.<theme>>.<space>. Non-colour
// categories (Phase 4): tokens.<format>.<category>.global — colour paths are unchanged.
// Figma is not in the bundle.
//
// Runs first in `build` (before tsup bundles src/index.ts). Deterministic.

import { writeFileSync } from 'node:fs'

const SPACES = ['hex', 'hsl', 'oklch', 'rgb']
const THEMES = ['masterbrand', 'fuchsia-blue', 'fuchsia-orange', 'data-visualisation']
// Non-colour categories and the layers each exposes. typography has a semantic layer
// (the Phase 4c composites) on top of its global primitives.
const CATEGORIES = [
  { key: 'space', layers: ['global'] },
  { key: 'radius', layers: ['global'] },
  { key: 'breakpoints', layers: ['global'] },
  { key: 'typography', layers: ['global', 'semantic'] },
]

const cap = (s) => s[0].toUpperCase() + s.slice(1)
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase())

// group: where it nests in the tokens object; tokensDir: path under ../tokens for `colors`.
const ENTITIES = [
  { v: 'global', formatDir: 'global', tokensDir: 'global/color', group: 'global' },
  { v: 'semantic', formatDir: 'semantic', tokensDir: 'semantic/color', group: 'semantic' },
  ...THEMES.map((t) => ({
    v: camel(t),
    formatDir: `themes/${t}`,
    tokensDir: `themes/color/${t}`,
    group: 'themes',
    themeKey: t,
  })),
]

// format key -> { infix, ext, require? }. `colors` reads token views from ../tokens; everything
// else reads its own generated output. colors + json use require (JSON); the rest import as text/
// modules. ts files are .ts but imported with a .js specifier (NodeNext).
const FORMATS = [
  { key: 'colors', infix: 'Color' },
  { key: 'css', infix: 'Css', ext: 'css' },
  { key: 'js', infix: 'Js', ext: 'js' },
  { key: 'json', infix: 'Json' },
  { key: 'less', infix: 'Less', ext: 'less' },
  { key: 'scss', infix: 'Scss', ext: 'scss' },
  { key: 'tailwind', infix: 'Tailwind', ext: 'css' },
  { key: 'ts', infix: 'Ts', ext: 'js' },
]

const varName = (fmt, ent, space) => `${ent.v}${fmt.infix}${cap(space)}`

const importLine = (fmt, ent, space) => {
  const v = varName(fmt, ent, space)
  if (fmt.key === 'colors')
    return `const ${v} = require('../tokens/${ent.tokensDir}/${space}.json')`
  if (fmt.key === 'json')
    return `const ${v} = require('./json/colors/${ent.formatDir}/${space}.json')`
  return `import * as ${v} from './${fmt.key}/colors/${ent.formatDir}/${space}.${fmt.ext}'`
}

// Category outputs exist for every style format; `colors` is colour-specific (raw category
// DTCG is consumable via the ./tokens/* subpath exports instead). The semantic typography
// composites have no tailwind output (Tailwind v4 has no composite namespace).
const categoryLayers = (fmt, category) =>
  category.layers.filter((layer) => !(layer === 'semantic' && fmt.key === 'tailwind'))
const categoryVarName = (fmt, category, layer) => `${camel(category.key)}${fmt.infix}${cap(layer)}`
const categoryImportLine = (fmt, category, layer) => {
  const v = categoryVarName(fmt, category, layer)
  if (fmt.key === 'json') return `const ${v} = require('./json/${category.key}/${layer}.json')`
  return `import * as ${v} from './${fmt.key}/${category.key}/${layer}.${fmt.ext}'`
}

let out = '/* eslint-disable */\n// Generated by scripts/build-index.mjs — do not edit.\n\n'
for (const fmt of FORMATS) {
  for (const ent of ENTITIES) for (const space of SPACES) out += `${importLine(fmt, ent, space)}\n`
  if (fmt.key !== 'colors')
    for (const category of CATEGORIES)
      for (const layer of categoryLayers(fmt, category))
        out += `${categoryImportLine(fmt, category, layer)}\n`
  out += '\n'
}

const spaceObj = (fmt, ent) =>
  `{ ${SPACES.map((s) => `${s}: ${varName(fmt, ent, s)}`).join(', ')} }`
const formatTree = (fmt) => {
  const get = (group) => ENTITIES.find((e) => e.group === group)
  const themes = ENTITIES.filter((e) => e.group === 'themes')
    .map((t) => `      ${JSON.stringify(t.themeKey)}: ${spaceObj(fmt, t)},`)
    .join('\n')
  const categories =
    fmt.key === 'colors'
      ? []
      : CATEGORIES.map((c) => {
          const layers = categoryLayers(fmt, c)
            .map((layer) => `${layer}: ${categoryVarName(fmt, c, layer)}`)
            .join(', ')
          return `    ${camel(c.key)}: { ${layers} },`
        })
  return [
    `  ${fmt.key}: {`,
    `    global: ${spaceObj(fmt, get('global'))},`,
    `    semantic: ${spaceObj(fmt, get('semantic'))},`,
    `    themes: {`,
    themes,
    `    },`,
    ...categories,
    `  },`,
  ].join('\n')
}

out += `export const tokens = {\n${FORMATS.map(formatTree).join('\n')}\n}\n\n`

out += `export const colorTokens = tokens.colors
export const cssTokens = tokens.css
export const jsTokens = tokens.js
export const jsonTokens = tokens.json
export const lessTokens = tokens.less
export const scssTokens = tokens.scss
export const tailwindTokens = tokens.tailwind
export const tsTokens = tokens.ts

export const brand = {
  iconDark: { ico: './brand/icon-dark.ico', png: './brand/icon-dark.png', svg: './brand/icon-dark.svg' },
  iconLight: { ico: './brand/icon-light.ico', png: './brand/icon-light.png', svg: './brand/icon-light.svg' },
  icon: './brand/icon.svg',
  logo: { png: './brand/logo.png', svg: './brand/logo.svg' },
  placeholder: './brand/placeholder.svg',
}
`

writeFileSync('src/index.ts', out)
console.log('✅ Generated src/index.ts')
