// Phase 2 cut-over: generate the per-format style outputs (css/scss/less/js/ts/json/figma/
// tailwind) from the DTCG tokens via Style Dictionary, writing them INTO src/ so the root
// bundle (src/index.ts imports them) and copy-styles (copies them to dist/) pick them up.
//
// This replaces the previously hand-authored src/* format files with generated ones —
// tokens/** is now the single source.
//
// Cleanup: SD only writes the destinations it declares, so a file that stops being generated
// (e.g. after dropping a colour space) would otherwise linger in src/ and still be published.
// To avoid that, we first remove the SD-OWNED destination directories (derived from the config
// destinations) and regenerate them. Everything else is preserved because it lives in OTHER
// directories that are never destinations:
//   - orphan Tailwind themes (data-visualisation, fuchsia-orange, fuchsia-blue) — pending M5
//   - prism.css, brand assets, src/index.ts

import StyleDictionary from 'style-dictionary'
import { execFileSync } from 'node:child_process'
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import configs from '../build/style-dictionary.config.mjs'

const SRC = 'src'

// Point every platform at src/ and collect the directories SD owns.
const ownedDirs = new Set()
for (const config of configs) {
  for (const platform of Object.values(config.platforms)) {
    platform.buildPath = `${SRC}/`
    for (const file of platform.files) ownedDirs.add(dirname(file.destination))
  }
}

// Clean the SD-owned directories so no-longer-generated files don't stick around.
for (const dir of ownedDirs) {
  rmSync(resolve(SRC, dir), { recursive: true, force: true })
}

for (const config of configs) {
  await new StyleDictionary(config).buildAllPlatforms()
}

// One-import Tailwind v4 preset (roadmap 2a): concatenates the generated per-category
// Tailwind outputs so consumers write a single
//   @import '@nswds/tokens/tailwind/preset.css';
// instead of eight. Concatenation (not @import) so the file is self-contained under any
// build tooling; Tailwind v4 merges repeated @theme blocks. Colours use the hex view —
// the package's default representation. Themes are deliberately EXCLUDED: they are
// alternative brandings that define the same family names (primary/accent/...), so
// consumers opt into exactly one, e.g.
//   @import '@nswds/tokens/tailwind/colors/themes/masterbrand/hex.css';
const PRESET_PARTS = [
  'tailwind/colors/global/hex.css',
  'tailwind/colors/semantic/hex.css',
  'tailwind/space/global.css',
  'tailwind/radius/global.css',
  'tailwind/breakpoints/global.css',
  'tailwind/typography/global.css',
  'tailwind/border/global.css',
  'tailwind/shadow/global.css',
]
const preset = [
  '/* Generated by scripts/generate-styles.mjs — do not edit.',
  ' * One-import Tailwind v4 preset: global + semantic colours (hex) and every',
  ' * non-colour category. Themes are not included — they define the same family',
  ' * names as one another, so import exactly one alongside this file, e.g.',
  " *   @import '@nswds/tokens/tailwind/colors/themes/masterbrand/hex.css';",
  ' */',
  ...PRESET_PARTS.map((part) => `\n/* ── ${part} ── */\n${readFileSync(`${SRC}/${part}`, 'utf8')}`),
].join('\n')
writeFileSync(`${SRC}/tailwind/preset.css`, preset)

// The generated js/ts modules are linted by the repo's Prettier config, whose wrapping
// heuristics (short-key attachment, print-width breaks for long font stacks) aren't worth
// reimplementing in the formats — run Prettier itself as the final generation step so the
// outputs are conformant by construction. Deterministic, so check:dist is unaffected.
execFileSync('npx', ['prettier', '--write', '--log-level', 'warn', `${SRC}/js`, `${SRC}/ts`], {
  stdio: 'inherit',
})

console.log('✅ Generated src/* style outputs from tokens/ via Style Dictionary')
