/* eslint-disable */
// Generated by scripts/build-index.mjs — do not edit.

const globalColorHex = require('../tokens/global/color/hex.json')
const globalColorHsl = require('../tokens/global/color/hsl.json')
const globalColorOklch = require('../tokens/global/color/oklch.json')
const globalColorRgb = require('../tokens/global/color/rgb.json')
const semanticColorHex = require('../tokens/semantic/color/hex.json')
const semanticColorHsl = require('../tokens/semantic/color/hsl.json')
const semanticColorOklch = require('../tokens/semantic/color/oklch.json')
const semanticColorRgb = require('../tokens/semantic/color/rgb.json')
const masterbrandColorHex = require('../tokens/themes/color/masterbrand/hex.json')
const masterbrandColorHsl = require('../tokens/themes/color/masterbrand/hsl.json')
const masterbrandColorOklch = require('../tokens/themes/color/masterbrand/oklch.json')
const masterbrandColorRgb = require('../tokens/themes/color/masterbrand/rgb.json')
const fuchsiaBlueColorHex = require('../tokens/themes/color/fuchsia-blue/hex.json')
const fuchsiaBlueColorHsl = require('../tokens/themes/color/fuchsia-blue/hsl.json')
const fuchsiaBlueColorOklch = require('../tokens/themes/color/fuchsia-blue/oklch.json')
const fuchsiaBlueColorRgb = require('../tokens/themes/color/fuchsia-blue/rgb.json')
const fuchsiaOrangeColorHex = require('../tokens/themes/color/fuchsia-orange/hex.json')
const fuchsiaOrangeColorHsl = require('../tokens/themes/color/fuchsia-orange/hsl.json')
const fuchsiaOrangeColorOklch = require('../tokens/themes/color/fuchsia-orange/oklch.json')
const fuchsiaOrangeColorRgb = require('../tokens/themes/color/fuchsia-orange/rgb.json')
const dataVisualisationColorHex = require('../tokens/themes/color/data-visualisation/hex.json')
const dataVisualisationColorHsl = require('../tokens/themes/color/data-visualisation/hsl.json')
const dataVisualisationColorOklch = require('../tokens/themes/color/data-visualisation/oklch.json')
const dataVisualisationColorRgb = require('../tokens/themes/color/data-visualisation/rgb.json')

import * as globalCssHex from './css/colors/global/hex.css'
import * as globalCssHsl from './css/colors/global/hsl.css'
import * as globalCssOklch from './css/colors/global/oklch.css'
import * as globalCssRgb from './css/colors/global/rgb.css'
import * as semanticCssHex from './css/colors/semantic/hex.css'
import * as semanticCssHsl from './css/colors/semantic/hsl.css'
import * as semanticCssOklch from './css/colors/semantic/oklch.css'
import * as semanticCssRgb from './css/colors/semantic/rgb.css'
import * as masterbrandCssHex from './css/colors/themes/masterbrand/hex.css'
import * as masterbrandCssHsl from './css/colors/themes/masterbrand/hsl.css'
import * as masterbrandCssOklch from './css/colors/themes/masterbrand/oklch.css'
import * as masterbrandCssRgb from './css/colors/themes/masterbrand/rgb.css'
import * as fuchsiaBlueCssHex from './css/colors/themes/fuchsia-blue/hex.css'
import * as fuchsiaBlueCssHsl from './css/colors/themes/fuchsia-blue/hsl.css'
import * as fuchsiaBlueCssOklch from './css/colors/themes/fuchsia-blue/oklch.css'
import * as fuchsiaBlueCssRgb from './css/colors/themes/fuchsia-blue/rgb.css'
import * as fuchsiaOrangeCssHex from './css/colors/themes/fuchsia-orange/hex.css'
import * as fuchsiaOrangeCssHsl from './css/colors/themes/fuchsia-orange/hsl.css'
import * as fuchsiaOrangeCssOklch from './css/colors/themes/fuchsia-orange/oklch.css'
import * as fuchsiaOrangeCssRgb from './css/colors/themes/fuchsia-orange/rgb.css'
import * as dataVisualisationCssHex from './css/colors/themes/data-visualisation/hex.css'
import * as dataVisualisationCssHsl from './css/colors/themes/data-visualisation/hsl.css'
import * as dataVisualisationCssOklch from './css/colors/themes/data-visualisation/oklch.css'
import * as dataVisualisationCssRgb from './css/colors/themes/data-visualisation/rgb.css'

import * as globalJsHex from './js/colors/global/hex.js'
import * as globalJsHsl from './js/colors/global/hsl.js'
import * as globalJsOklch from './js/colors/global/oklch.js'
import * as globalJsRgb from './js/colors/global/rgb.js'
import * as semanticJsHex from './js/colors/semantic/hex.js'
import * as semanticJsHsl from './js/colors/semantic/hsl.js'
import * as semanticJsOklch from './js/colors/semantic/oklch.js'
import * as semanticJsRgb from './js/colors/semantic/rgb.js'
import * as masterbrandJsHex from './js/colors/themes/masterbrand/hex.js'
import * as masterbrandJsHsl from './js/colors/themes/masterbrand/hsl.js'
import * as masterbrandJsOklch from './js/colors/themes/masterbrand/oklch.js'
import * as masterbrandJsRgb from './js/colors/themes/masterbrand/rgb.js'
import * as fuchsiaBlueJsHex from './js/colors/themes/fuchsia-blue/hex.js'
import * as fuchsiaBlueJsHsl from './js/colors/themes/fuchsia-blue/hsl.js'
import * as fuchsiaBlueJsOklch from './js/colors/themes/fuchsia-blue/oklch.js'
import * as fuchsiaBlueJsRgb from './js/colors/themes/fuchsia-blue/rgb.js'
import * as fuchsiaOrangeJsHex from './js/colors/themes/fuchsia-orange/hex.js'
import * as fuchsiaOrangeJsHsl from './js/colors/themes/fuchsia-orange/hsl.js'
import * as fuchsiaOrangeJsOklch from './js/colors/themes/fuchsia-orange/oklch.js'
import * as fuchsiaOrangeJsRgb from './js/colors/themes/fuchsia-orange/rgb.js'
import * as dataVisualisationJsHex from './js/colors/themes/data-visualisation/hex.js'
import * as dataVisualisationJsHsl from './js/colors/themes/data-visualisation/hsl.js'
import * as dataVisualisationJsOklch from './js/colors/themes/data-visualisation/oklch.js'
import * as dataVisualisationJsRgb from './js/colors/themes/data-visualisation/rgb.js'

const globalJsonHex = require('./json/colors/global/hex.json')
const globalJsonHsl = require('./json/colors/global/hsl.json')
const globalJsonOklch = require('./json/colors/global/oklch.json')
const globalJsonRgb = require('./json/colors/global/rgb.json')
const semanticJsonHex = require('./json/colors/semantic/hex.json')
const semanticJsonHsl = require('./json/colors/semantic/hsl.json')
const semanticJsonOklch = require('./json/colors/semantic/oklch.json')
const semanticJsonRgb = require('./json/colors/semantic/rgb.json')
const masterbrandJsonHex = require('./json/colors/themes/masterbrand/hex.json')
const masterbrandJsonHsl = require('./json/colors/themes/masterbrand/hsl.json')
const masterbrandJsonOklch = require('./json/colors/themes/masterbrand/oklch.json')
const masterbrandJsonRgb = require('./json/colors/themes/masterbrand/rgb.json')
const fuchsiaBlueJsonHex = require('./json/colors/themes/fuchsia-blue/hex.json')
const fuchsiaBlueJsonHsl = require('./json/colors/themes/fuchsia-blue/hsl.json')
const fuchsiaBlueJsonOklch = require('./json/colors/themes/fuchsia-blue/oklch.json')
const fuchsiaBlueJsonRgb = require('./json/colors/themes/fuchsia-blue/rgb.json')
const fuchsiaOrangeJsonHex = require('./json/colors/themes/fuchsia-orange/hex.json')
const fuchsiaOrangeJsonHsl = require('./json/colors/themes/fuchsia-orange/hsl.json')
const fuchsiaOrangeJsonOklch = require('./json/colors/themes/fuchsia-orange/oklch.json')
const fuchsiaOrangeJsonRgb = require('./json/colors/themes/fuchsia-orange/rgb.json')
const dataVisualisationJsonHex = require('./json/colors/themes/data-visualisation/hex.json')
const dataVisualisationJsonHsl = require('./json/colors/themes/data-visualisation/hsl.json')
const dataVisualisationJsonOklch = require('./json/colors/themes/data-visualisation/oklch.json')
const dataVisualisationJsonRgb = require('./json/colors/themes/data-visualisation/rgb.json')

import * as globalLessHex from './less/colors/global/hex.less'
import * as globalLessHsl from './less/colors/global/hsl.less'
import * as globalLessOklch from './less/colors/global/oklch.less'
import * as globalLessRgb from './less/colors/global/rgb.less'
import * as semanticLessHex from './less/colors/semantic/hex.less'
import * as semanticLessHsl from './less/colors/semantic/hsl.less'
import * as semanticLessOklch from './less/colors/semantic/oklch.less'
import * as semanticLessRgb from './less/colors/semantic/rgb.less'
import * as masterbrandLessHex from './less/colors/themes/masterbrand/hex.less'
import * as masterbrandLessHsl from './less/colors/themes/masterbrand/hsl.less'
import * as masterbrandLessOklch from './less/colors/themes/masterbrand/oklch.less'
import * as masterbrandLessRgb from './less/colors/themes/masterbrand/rgb.less'
import * as fuchsiaBlueLessHex from './less/colors/themes/fuchsia-blue/hex.less'
import * as fuchsiaBlueLessHsl from './less/colors/themes/fuchsia-blue/hsl.less'
import * as fuchsiaBlueLessOklch from './less/colors/themes/fuchsia-blue/oklch.less'
import * as fuchsiaBlueLessRgb from './less/colors/themes/fuchsia-blue/rgb.less'
import * as fuchsiaOrangeLessHex from './less/colors/themes/fuchsia-orange/hex.less'
import * as fuchsiaOrangeLessHsl from './less/colors/themes/fuchsia-orange/hsl.less'
import * as fuchsiaOrangeLessOklch from './less/colors/themes/fuchsia-orange/oklch.less'
import * as fuchsiaOrangeLessRgb from './less/colors/themes/fuchsia-orange/rgb.less'
import * as dataVisualisationLessHex from './less/colors/themes/data-visualisation/hex.less'
import * as dataVisualisationLessHsl from './less/colors/themes/data-visualisation/hsl.less'
import * as dataVisualisationLessOklch from './less/colors/themes/data-visualisation/oklch.less'
import * as dataVisualisationLessRgb from './less/colors/themes/data-visualisation/rgb.less'

import * as globalScssHex from './scss/colors/global/hex.scss'
import * as globalScssHsl from './scss/colors/global/hsl.scss'
import * as globalScssOklch from './scss/colors/global/oklch.scss'
import * as globalScssRgb from './scss/colors/global/rgb.scss'
import * as semanticScssHex from './scss/colors/semantic/hex.scss'
import * as semanticScssHsl from './scss/colors/semantic/hsl.scss'
import * as semanticScssOklch from './scss/colors/semantic/oklch.scss'
import * as semanticScssRgb from './scss/colors/semantic/rgb.scss'
import * as masterbrandScssHex from './scss/colors/themes/masterbrand/hex.scss'
import * as masterbrandScssHsl from './scss/colors/themes/masterbrand/hsl.scss'
import * as masterbrandScssOklch from './scss/colors/themes/masterbrand/oklch.scss'
import * as masterbrandScssRgb from './scss/colors/themes/masterbrand/rgb.scss'
import * as fuchsiaBlueScssHex from './scss/colors/themes/fuchsia-blue/hex.scss'
import * as fuchsiaBlueScssHsl from './scss/colors/themes/fuchsia-blue/hsl.scss'
import * as fuchsiaBlueScssOklch from './scss/colors/themes/fuchsia-blue/oklch.scss'
import * as fuchsiaBlueScssRgb from './scss/colors/themes/fuchsia-blue/rgb.scss'
import * as fuchsiaOrangeScssHex from './scss/colors/themes/fuchsia-orange/hex.scss'
import * as fuchsiaOrangeScssHsl from './scss/colors/themes/fuchsia-orange/hsl.scss'
import * as fuchsiaOrangeScssOklch from './scss/colors/themes/fuchsia-orange/oklch.scss'
import * as fuchsiaOrangeScssRgb from './scss/colors/themes/fuchsia-orange/rgb.scss'
import * as dataVisualisationScssHex from './scss/colors/themes/data-visualisation/hex.scss'
import * as dataVisualisationScssHsl from './scss/colors/themes/data-visualisation/hsl.scss'
import * as dataVisualisationScssOklch from './scss/colors/themes/data-visualisation/oklch.scss'
import * as dataVisualisationScssRgb from './scss/colors/themes/data-visualisation/rgb.scss'

import * as globalTailwindHex from './tailwind/colors/global/hex.css'
import * as globalTailwindHsl from './tailwind/colors/global/hsl.css'
import * as globalTailwindOklch from './tailwind/colors/global/oklch.css'
import * as globalTailwindRgb from './tailwind/colors/global/rgb.css'
import * as semanticTailwindHex from './tailwind/colors/semantic/hex.css'
import * as semanticTailwindHsl from './tailwind/colors/semantic/hsl.css'
import * as semanticTailwindOklch from './tailwind/colors/semantic/oklch.css'
import * as semanticTailwindRgb from './tailwind/colors/semantic/rgb.css'
import * as masterbrandTailwindHex from './tailwind/colors/themes/masterbrand/hex.css'
import * as masterbrandTailwindHsl from './tailwind/colors/themes/masterbrand/hsl.css'
import * as masterbrandTailwindOklch from './tailwind/colors/themes/masterbrand/oklch.css'
import * as masterbrandTailwindRgb from './tailwind/colors/themes/masterbrand/rgb.css'
import * as fuchsiaBlueTailwindHex from './tailwind/colors/themes/fuchsia-blue/hex.css'
import * as fuchsiaBlueTailwindHsl from './tailwind/colors/themes/fuchsia-blue/hsl.css'
import * as fuchsiaBlueTailwindOklch from './tailwind/colors/themes/fuchsia-blue/oklch.css'
import * as fuchsiaBlueTailwindRgb from './tailwind/colors/themes/fuchsia-blue/rgb.css'
import * as fuchsiaOrangeTailwindHex from './tailwind/colors/themes/fuchsia-orange/hex.css'
import * as fuchsiaOrangeTailwindHsl from './tailwind/colors/themes/fuchsia-orange/hsl.css'
import * as fuchsiaOrangeTailwindOklch from './tailwind/colors/themes/fuchsia-orange/oklch.css'
import * as fuchsiaOrangeTailwindRgb from './tailwind/colors/themes/fuchsia-orange/rgb.css'
import * as dataVisualisationTailwindHex from './tailwind/colors/themes/data-visualisation/hex.css'
import * as dataVisualisationTailwindHsl from './tailwind/colors/themes/data-visualisation/hsl.css'
import * as dataVisualisationTailwindOklch from './tailwind/colors/themes/data-visualisation/oklch.css'
import * as dataVisualisationTailwindRgb from './tailwind/colors/themes/data-visualisation/rgb.css'

import * as globalTsHex from './ts/colors/global/hex.js'
import * as globalTsHsl from './ts/colors/global/hsl.js'
import * as globalTsOklch from './ts/colors/global/oklch.js'
import * as globalTsRgb from './ts/colors/global/rgb.js'
import * as semanticTsHex from './ts/colors/semantic/hex.js'
import * as semanticTsHsl from './ts/colors/semantic/hsl.js'
import * as semanticTsOklch from './ts/colors/semantic/oklch.js'
import * as semanticTsRgb from './ts/colors/semantic/rgb.js'
import * as masterbrandTsHex from './ts/colors/themes/masterbrand/hex.js'
import * as masterbrandTsHsl from './ts/colors/themes/masterbrand/hsl.js'
import * as masterbrandTsOklch from './ts/colors/themes/masterbrand/oklch.js'
import * as masterbrandTsRgb from './ts/colors/themes/masterbrand/rgb.js'
import * as fuchsiaBlueTsHex from './ts/colors/themes/fuchsia-blue/hex.js'
import * as fuchsiaBlueTsHsl from './ts/colors/themes/fuchsia-blue/hsl.js'
import * as fuchsiaBlueTsOklch from './ts/colors/themes/fuchsia-blue/oklch.js'
import * as fuchsiaBlueTsRgb from './ts/colors/themes/fuchsia-blue/rgb.js'
import * as fuchsiaOrangeTsHex from './ts/colors/themes/fuchsia-orange/hex.js'
import * as fuchsiaOrangeTsHsl from './ts/colors/themes/fuchsia-orange/hsl.js'
import * as fuchsiaOrangeTsOklch from './ts/colors/themes/fuchsia-orange/oklch.js'
import * as fuchsiaOrangeTsRgb from './ts/colors/themes/fuchsia-orange/rgb.js'
import * as dataVisualisationTsHex from './ts/colors/themes/data-visualisation/hex.js'
import * as dataVisualisationTsHsl from './ts/colors/themes/data-visualisation/hsl.js'
import * as dataVisualisationTsOklch from './ts/colors/themes/data-visualisation/oklch.js'
import * as dataVisualisationTsRgb from './ts/colors/themes/data-visualisation/rgb.js'

export const tokens = {
  colors: {
    global: { hex: globalColorHex, hsl: globalColorHsl, oklch: globalColorOklch, rgb: globalColorRgb },
    semantic: { hex: semanticColorHex, hsl: semanticColorHsl, oklch: semanticColorOklch, rgb: semanticColorRgb },
    themes: {
      "masterbrand": { hex: masterbrandColorHex, hsl: masterbrandColorHsl, oklch: masterbrandColorOklch, rgb: masterbrandColorRgb },
      "fuchsia-blue": { hex: fuchsiaBlueColorHex, hsl: fuchsiaBlueColorHsl, oklch: fuchsiaBlueColorOklch, rgb: fuchsiaBlueColorRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeColorHex, hsl: fuchsiaOrangeColorHsl, oklch: fuchsiaOrangeColorOklch, rgb: fuchsiaOrangeColorRgb },
      "data-visualisation": { hex: dataVisualisationColorHex, hsl: dataVisualisationColorHsl, oklch: dataVisualisationColorOklch, rgb: dataVisualisationColorRgb },
    },
  },
  css: {
    global: { hex: globalCssHex, hsl: globalCssHsl, oklch: globalCssOklch, rgb: globalCssRgb },
    semantic: { hex: semanticCssHex, hsl: semanticCssHsl, oklch: semanticCssOklch, rgb: semanticCssRgb },
    themes: {
      "masterbrand": { hex: masterbrandCssHex, hsl: masterbrandCssHsl, oklch: masterbrandCssOklch, rgb: masterbrandCssRgb },
      "fuchsia-blue": { hex: fuchsiaBlueCssHex, hsl: fuchsiaBlueCssHsl, oklch: fuchsiaBlueCssOklch, rgb: fuchsiaBlueCssRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeCssHex, hsl: fuchsiaOrangeCssHsl, oklch: fuchsiaOrangeCssOklch, rgb: fuchsiaOrangeCssRgb },
      "data-visualisation": { hex: dataVisualisationCssHex, hsl: dataVisualisationCssHsl, oklch: dataVisualisationCssOklch, rgb: dataVisualisationCssRgb },
    },
  },
  js: {
    global: { hex: globalJsHex, hsl: globalJsHsl, oklch: globalJsOklch, rgb: globalJsRgb },
    semantic: { hex: semanticJsHex, hsl: semanticJsHsl, oklch: semanticJsOklch, rgb: semanticJsRgb },
    themes: {
      "masterbrand": { hex: masterbrandJsHex, hsl: masterbrandJsHsl, oklch: masterbrandJsOklch, rgb: masterbrandJsRgb },
      "fuchsia-blue": { hex: fuchsiaBlueJsHex, hsl: fuchsiaBlueJsHsl, oklch: fuchsiaBlueJsOklch, rgb: fuchsiaBlueJsRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeJsHex, hsl: fuchsiaOrangeJsHsl, oklch: fuchsiaOrangeJsOklch, rgb: fuchsiaOrangeJsRgb },
      "data-visualisation": { hex: dataVisualisationJsHex, hsl: dataVisualisationJsHsl, oklch: dataVisualisationJsOklch, rgb: dataVisualisationJsRgb },
    },
  },
  json: {
    global: { hex: globalJsonHex, hsl: globalJsonHsl, oklch: globalJsonOklch, rgb: globalJsonRgb },
    semantic: { hex: semanticJsonHex, hsl: semanticJsonHsl, oklch: semanticJsonOklch, rgb: semanticJsonRgb },
    themes: {
      "masterbrand": { hex: masterbrandJsonHex, hsl: masterbrandJsonHsl, oklch: masterbrandJsonOklch, rgb: masterbrandJsonRgb },
      "fuchsia-blue": { hex: fuchsiaBlueJsonHex, hsl: fuchsiaBlueJsonHsl, oklch: fuchsiaBlueJsonOklch, rgb: fuchsiaBlueJsonRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeJsonHex, hsl: fuchsiaOrangeJsonHsl, oklch: fuchsiaOrangeJsonOklch, rgb: fuchsiaOrangeJsonRgb },
      "data-visualisation": { hex: dataVisualisationJsonHex, hsl: dataVisualisationJsonHsl, oklch: dataVisualisationJsonOklch, rgb: dataVisualisationJsonRgb },
    },
  },
  less: {
    global: { hex: globalLessHex, hsl: globalLessHsl, oklch: globalLessOklch, rgb: globalLessRgb },
    semantic: { hex: semanticLessHex, hsl: semanticLessHsl, oklch: semanticLessOklch, rgb: semanticLessRgb },
    themes: {
      "masterbrand": { hex: masterbrandLessHex, hsl: masterbrandLessHsl, oklch: masterbrandLessOklch, rgb: masterbrandLessRgb },
      "fuchsia-blue": { hex: fuchsiaBlueLessHex, hsl: fuchsiaBlueLessHsl, oklch: fuchsiaBlueLessOklch, rgb: fuchsiaBlueLessRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeLessHex, hsl: fuchsiaOrangeLessHsl, oklch: fuchsiaOrangeLessOklch, rgb: fuchsiaOrangeLessRgb },
      "data-visualisation": { hex: dataVisualisationLessHex, hsl: dataVisualisationLessHsl, oklch: dataVisualisationLessOklch, rgb: dataVisualisationLessRgb },
    },
  },
  scss: {
    global: { hex: globalScssHex, hsl: globalScssHsl, oklch: globalScssOklch, rgb: globalScssRgb },
    semantic: { hex: semanticScssHex, hsl: semanticScssHsl, oklch: semanticScssOklch, rgb: semanticScssRgb },
    themes: {
      "masterbrand": { hex: masterbrandScssHex, hsl: masterbrandScssHsl, oklch: masterbrandScssOklch, rgb: masterbrandScssRgb },
      "fuchsia-blue": { hex: fuchsiaBlueScssHex, hsl: fuchsiaBlueScssHsl, oklch: fuchsiaBlueScssOklch, rgb: fuchsiaBlueScssRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeScssHex, hsl: fuchsiaOrangeScssHsl, oklch: fuchsiaOrangeScssOklch, rgb: fuchsiaOrangeScssRgb },
      "data-visualisation": { hex: dataVisualisationScssHex, hsl: dataVisualisationScssHsl, oklch: dataVisualisationScssOklch, rgb: dataVisualisationScssRgb },
    },
  },
  tailwind: {
    global: { hex: globalTailwindHex, hsl: globalTailwindHsl, oklch: globalTailwindOklch, rgb: globalTailwindRgb },
    semantic: { hex: semanticTailwindHex, hsl: semanticTailwindHsl, oklch: semanticTailwindOklch, rgb: semanticTailwindRgb },
    themes: {
      "masterbrand": { hex: masterbrandTailwindHex, hsl: masterbrandTailwindHsl, oklch: masterbrandTailwindOklch, rgb: masterbrandTailwindRgb },
      "fuchsia-blue": { hex: fuchsiaBlueTailwindHex, hsl: fuchsiaBlueTailwindHsl, oklch: fuchsiaBlueTailwindOklch, rgb: fuchsiaBlueTailwindRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeTailwindHex, hsl: fuchsiaOrangeTailwindHsl, oklch: fuchsiaOrangeTailwindOklch, rgb: fuchsiaOrangeTailwindRgb },
      "data-visualisation": { hex: dataVisualisationTailwindHex, hsl: dataVisualisationTailwindHsl, oklch: dataVisualisationTailwindOklch, rgb: dataVisualisationTailwindRgb },
    },
  },
  ts: {
    global: { hex: globalTsHex, hsl: globalTsHsl, oklch: globalTsOklch, rgb: globalTsRgb },
    semantic: { hex: semanticTsHex, hsl: semanticTsHsl, oklch: semanticTsOklch, rgb: semanticTsRgb },
    themes: {
      "masterbrand": { hex: masterbrandTsHex, hsl: masterbrandTsHsl, oklch: masterbrandTsOklch, rgb: masterbrandTsRgb },
      "fuchsia-blue": { hex: fuchsiaBlueTsHex, hsl: fuchsiaBlueTsHsl, oklch: fuchsiaBlueTsOklch, rgb: fuchsiaBlueTsRgb },
      "fuchsia-orange": { hex: fuchsiaOrangeTsHex, hsl: fuchsiaOrangeTsHsl, oklch: fuchsiaOrangeTsOklch, rgb: fuchsiaOrangeTsRgb },
      "data-visualisation": { hex: dataVisualisationTsHex, hsl: dataVisualisationTsHsl, oklch: dataVisualisationTsOklch, rgb: dataVisualisationTsRgb },
    },
  },
}

export const colorTokens = tokens.colors
export const cssTokens = tokens.css
export const jsTokens = tokens.js
export const jsonTokens = tokens.json
export const lessTokens = tokens.less
export const scssTokens = tokens.scss
export const tailwindTokens = tokens.tailwind
export const tsTokens = tokens.ts

export const brand = {
  iconDark: { ico: './brand/icon-dark.ico', png: './brand/icon-dark.png', svg: './brand/icon-dark.svg' },
  iconLight: { ico: './brand/icon-light.ico', png: './brand/icon-light.png', svg: './brand/icon-light.svg' },
  icon: './brand/icon.svg',
  logo: { png: './brand/logo.png', svg: './brand/logo.svg' },
  placeholder: './brand/placeholder.svg',
}
